name: CI with Caching

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-with-cache:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up 'uv' (or any other necessary setup)
      - name: Set up uv
        uses: astral-sh/setup-uv@v5
      
      # Create a virtual environment
      - name: Create virtual environment
        run: uv venv

      # Cache step - caching dependencies using actions/cache
      - name: Cache uv dependencies
        uses: actions/cache@v4
        id: cache-uv
        with:
          path: ~/.cache/uv    # The path to be cached
          key: cache-ac39293   # Cache key (use a consistent key for the cache)

      # Install dependencies after the cache
      - name: Install dependencies
        run: uv pip install -r requirements.txt

      # Prime Cache step - checks the cache hit/miss and echoes a message
      - name: prime-cache-ac39293
        run: |
          if [[ "${{ steps.cache-uv.outputs.cache-hit }}" == "true" ]]; then
            echo "Cache hit! Dependencies were restored."
          else
            echo "Cache miss. Dependencies were installed and cache will be saved."
          fi
